---
apiVersion: v1
kind: Service
metadata:
  name     : mysql-service
  labels:
    app: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 34000
      targetPort: 3306
  type: ClusterIP
