apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-collector-deployment
  namespace: test-namespace
  labels:
    app: api-depl-lab

spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: fusionapi
          image: coolenov/fusion-api-collector:latest
          ports:
            - containerPort: 10000