apiVersion: v1
kind: Service
metadata:
  name: midjourney-service
  labels:
    app: midjourney-service
spec:
  type: ClusterIP
  selector:
    app: midjourney
  ports:
    - port: 34003
      targetPort: 9020
      protocol: TCP
