apiVersion: v1
kind: Service
metadata:
  name: midjourney
  labels:
    app: midjourney
spec:
  type: ClusterIP
  selector:
    app: midjourney
  ports:
    - port: 9020
      targetPort: 9020
      protocol: TCP
