---
- hosts: master
  gather_facts: true
  vars:
    app_path      : /kuber

  tasks:
    - name : "delete old folder"
      shell: rm -r Fusion-kuber-deploy
      ignore_errors: yes

    - name : "git clone"
      shell: git clone https://github.com/Coolenov/Fusion-kuber-deploy
