apiVersion: apps/v1
kind: Deployment
metadata:
  name: uanews-deployment
  labels:
    app: uanews

spec:
  replicas: 2
  selector:
    matchLabels:
      app: uanews
    template:
      metadata:
        labels:
          app: uanews
      spec:
        containers:
          - name: uanews
            image: coolenov/fusion-uanews-api:latest
