apiVersion: v1
kind: Service
metadata:
  name: habr-ru-service
  namespace: test
  labels:
    app: habr-ru-service
spec:
  type: ClusterIP
  selector:
    app: habr-ru
  ports:
    - name      : app-listener
      port      : 11000
      targetPort: 8010
      protocol  : TCP
