apiVersion: v1
kind: Service
metadata:
  name: habr-ru-service
  labels:
    app: habr-ru-service
spec:
  type: ClusterIP
  selector:
    app: habr-ru
  ports:
    - port: 31010
      targetPort: 8010
      protocol: TCP
