---
apiVersion: v1
kind: Service
metadata:
  name     : habreng
  labels:
    app: habreng
spec:
  selector:
    app: habreng
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8020
      targetPort: 8020
  type: ClusterIP
