apiVersion: v1
kind: Service
metadata:
  name: midjourney-service
  namespace: test
  labels:
    app: midjourney-service
spec:
  type: ClusterIP
  selector:
    app: midjourney
    ports:
      - name      : app-listener
        port      : 11000
        targetPort: 9020
        protocol  : TCP
