apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot-deployment
  namespace: test-namespace
  labels:
    app: telegrambot-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: coolenov/fusion-telegrambot:latest
