apiVersion: apps/v1
kind: Deployment
metadata:
  name: uanews-deployment
  namespace: test-namespace
  labels:
    app: uanews-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: uanews
  template:
    metadata:
      labels:
        app: uanews
    spec:
      containers:
        - name: uanews
          image: coolenov/fusion-uanews-api:latest
          ports:
            - containerPort: 8030
