apiVersion: v1
kind: Service
metadata:
  name: uanews
  namespace: test
  labels:
    app: uanews
spec:
  type: ClusterIP
  selector:
    app: uanews
  ports:
    - name      : app-listener
      port      : 34004
      targetPort: 8030
      protocol  : TCP
