apiVersion: v1
kind: Service
metadata:
  name: uanews-service
  namespace: test
  labels:
    app: uanews-service
spec:
  type: ClusterIP
  selector:
    app: uanews
  ports:
    - name      : app-listener
      port      : 11000
      targetPort: 8030
      protocol  : TCP
