apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-collector-deployment
  namespace: test-namespace
  labels:
    app: collector-depl-lab

spec:
  replicas: 3
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: api-collector
          image: coolenov/fusion-api-collector:latest
