---
- name: Install packages
  hosts: k8s_cluster
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - prepare-hosts

- name: Install Control nodes
  hosts: masters[0]
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - install-master

- name: Install worker nodes
  hosts: workers
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - install-worker
