apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-habr-ru-deployment
  labels:
    app: api-habr-ru-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: habrru
  template:
    metadata:
      labels:
        app: habrru
    spec:
      containers:
        - name: habrru
          image: coolenov/fusion-habr-ru-api:latest
          ports:
            - containerPort: 8010
