apiVersion: v1
kind: Service
metadata:
  name: habrru
  labels:
    app: habrru
spec:
  type: ClusterIP
  selector:
    app: habrru
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
