---
- name: Prepare to Join
  include_tasks: prepare.yaml
  when: inventory_hostname == groups['masters'][0]


- name: Join another control nodes
  include_tasks: join.yaml
  when: inventory_hostname != groups['masters'][0]
