apiVersion: v1
kind: Service
metadata:
  name: api-collector-service
  labels:
    app: fusionapi
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 10000
      targetPort: 10000
      protocol: TCP
