apiVersion: v1
kind: Service
metadata:
  name: api-collector-service
  namespace: test
  labels:
    app: collector-service
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 7500
      targetPort: 10000
      protocol: TCP